### PR TITLE
More compact UI for config

### LINKED ISSUE #76: visual/practical improvements
- [x] move save button
- [x] do not abuse collapse system
- [x] factorize all touch and all analog in one section
- [x] merge sensor and output translator settings under axis setting and keep aside general output settings (like OSC address/port)
- [x] make HID logic
- [x] make thing look nicer (live sensor value, dropdown)
- [x] midi/HID settings not reactive to sensor mode (in note mode, things should grey out if in threshmode)
- [x] reorder axis lists (quick settings and dropdown

### PR DESCRIPTION
**Pull request by Leo-Nicolle**
# More compact UI for config
 
 Closes #76

### CODE REVIEW

**Comment by Leo-Nicolle** [comment]
@rupraph  This is what I have for now. :)

[Screencast from 2024-10-10 19-35-18.webm](https://github.com/user-attachments/assets/4f5839fe-998c-4052-a4b7-87d2a69ea79e)

Dont look at the moment when I open the board settings, the axis selector styles are applied to it, it is ugly.

**Comment by rupraph** [comment]
The structure is nice, that's what we need, we just have to make it a tad more sexy :)

Note: under OSC tab, IP and Port are general settings that will be put below the "axis specific setting"

a bit like 
image

**Comment by Leo-Nicolle** [comment]
Things are advancing: 
 - [x] quick config
 - [x] global OSC config
 - [x] Pipo settings
 - [x] move delete button to tab
 - [x] do something with the HID config
 - [x] Title for quick config ? 

[Screencast from 2024-10-11 21-21-54.webm](https://github.com/user-attachments/assets/9d0209a2-3f2d-4def-9453-cc0405f01ed7)


 - What should we do for HID ? Cause for now it is :vomiting_face: 
 - What do we do with the save button ? 
 - How do you like the quick config ? Maybe black stroke on the circles? 
 - How do we separate the global board config from the rest ? Just a white bg title on top of it ? 


Screenshot from 2024-10-11 21-31-19

**Comment by rupraph** [comment]
It starts to look like a friendly UI ! :)


### For Hid
- [x] it can be split. will also need a global HID section,  like OSC
- [x] there is some logic to implement to propose only the feaseable mappings for the axis:
we depend on: sensor mode and hid mode.

threshmode + keyboard : select between character (then field to input one) or arrow (then dropdown to choose)
threshmode + mouse : map only to left/right button
continuous + keyboard : warning message, not possible
continuous + mouse: map to mouse X or Y 

### For the save button
- [ ] I just realized we could retry something to make it disapear. Until we finalize the websocket config, still use the diff + timer solution to trigger a full save whenever a setting is changed (but never more than once every 2sec or so). So we get rid of the button. This is clearly not optimal but it can probably fly until we do the larger config update.

### For styling
I'll think about it, there are a few details we can likely improve. Quick config is likely ok like that. 

### Global conf
- [x] Regarding the global config, I am note sure.
~~Option 1 we have maybe a seperate menu, like in  vertical leftbar or something. And we also put the global Hid and osc config there.~~(for later)
Option 2 we indeed just put in its own section at the end, collapsible. Over time more items will be in this pipo gloabal config.  Likely the easier for now, what do you think ?

**Comment by rupraph** [comment]
Some minor improvements: 
image


Note: 
- sensor curent value should be displayed centered above the slider, with some vertical margin to make it l ook nicer.
- sections should likely have better coloring. 
- axis selector dropdown should have nicer style

**Pull request merged**
