### PR TITLE
Multiple configs

### PR DESCRIPTION
**Pull request by Leo-Nicolle**
# Multiple configs
 - [x] Added CRUD routes for config
 - [x] Remember previous config
 - [x] Add different platformio envs for each board
 - [x] Add a script to copy the right config into the data folder depending on the board
 - [x] Add scripts in package.json to make it easy to use  
 
## Pipo config page 
 - [x] Added tabs for different configs
 - [x] Added tab to create a new configs
 - [x] Switch between configs
 - [x] UI to rename configs
 - [x] UI to delete config

### CODE REVIEW

**Comment by Leo-Nicolle** [comment]
@rupraph  Ready for you to test ! 
There are a lots of changes (mainly the envs), I never use the vscode buttons, but there are nice scripts in the package.json to upload things depending on the boards.
### Preview:

https://github.com/user-attachments/assets/172621ad-f5aa-4cf8-90a9-179619acaf26

**Comment by Leo-Nicolle** [comment]
I don t know if we could force platformio not to duplicate the `.pio/libdeps` for each env, it inflates the repo sooo much. ( but at the same time we have to commit it because of all the small typos we have to fix in there)

**Comment by rupraph** [comment]
> @rupraph Ready for you to test ! There are a lots of changes (mainly the envs), I never use the vscode buttons, but there are nice scripts in the package.json to upload things depending on the boards.
> ### Preview:
> simplescreenrecorder-2024-08-12_22.37.29.mp4

Great !!
I see you had some fun styling the selector  !  

Regarding the envs, I don't really get why there are now 3 envs duplicated for each pipo when trying to improve the structure. I was expecting to keep one single environment, and only build the filesystem image depending on the pipo type, which is mostly where we require some differenciation, but I might be missing something.

Maybe we will have to call when you have time, because thing do not build anymore here Mr Buldozer :D 
You want me to test, but you break the base in the same branch haha 

Note: pio takes care of .pio/libdeps, you should certainly not manage or adapt this manually ! (but of course I want to track the changes in there)

**Comment by Leo-Nicolle** [comment]
Why 3 envs? 
  - To have be able to define PIPO_MOTION, PIPO_ANALOG or PIPO_RANGE at compilation time ( via compilation flags) 
  - To be able to copy the right config into the data folder at the build:fs stage.
 
We could do it in another way, I just *felt* like it was the Platformio way of doing things. 

What is broken ? On my machine everything compiles beautifully ! Let's have a call at noon :)

**Pull request closed without merging**
