### PR TITLE
Minmax sliders

### LINKED ISSUE #39: page width not reactive
When tested on a phone the width of the page does not scale so that the config fits the page.

### PR DESCRIPTION
**Pull request by Leo-Nicolle**
# Add min max sliders

 - [x] on the sensor limit min limit max
 - [x] other places? 

[Screencast from 2024-08-30 08-55-36.webm](https://github.com/user-attachments/assets/90f97ab8-b1a5-486a-897a-43cb4fc8b65a)

 - Closes #39

### CODE REVIEW

**Comment by rupraph** [comment]
other places could be on OSC limits and  midi min/max

Could be good to have the min and max value displayed on the slider, or the cursor value displayed when you move it ?

**Comment by Leo-Nicolle** [comment]
I think we should keep a way to edit the value manually ( with the keyboard) .
I can add the two values on each extremities as editable fields.  [Like that ?](https://excalidraw.com/#json=MQrjmkI7gwW7PJ8wMSeDV,vtHCwRSZ9MND13sFLhdhRg)

**Comment by rupraph** [comment]
You are right, always good to have a manual edit field. 
But we should anyway display the absolute min/max on the sides of the sliders, because those are not editable. would indind just put them in small at start and end of the slider. 
For the editable min/max, maybe those could be hidden. I like your proposal with the fields at each extremities, but then I am not sure we have enough space to fit this properly. Maybe simply having editable min/max fields on a same line below the slider is enough for now (and possibly collapse them ?) 
Something like that with the second line collapsible ? 
image

**Comment by Leo-Nicolle** [comment]
OOooh Okay I did not understand, I thought you were talking about the values, not the min/max. Your design is perfect !

**Comment by Leo-Nicolle** [comment]
### Better slider:
[Screencast from 2024-09-01 17-14-47.webm](https://github.com/user-attachments/assets/518a5b11-baae-4d04-ab9b-cd385c29eba9)

**Comment by Leo-Nicolle** [comment]
Also, I fixed some CSS, there were a lot of mess with paddings and margins.

**Pull request merged**
